name: Update Pull Request Description
author: nefrob
description: Add or update content in GitHub PR description.

inputs:
  content:
    description: Content to add to PR description.
    required: true
  contentIsFilePath:
    description: Whether the content is a filename or raw text.
    required: false
  regex:
    description: Regex to match and with content. Pass empty string to append.
    required: false
  token:
    description: GitHub secrets access token.
    required: true

runs:
  using: node16
  main: dist/index.js

branding:
  icon: align-left
  color: white